# Generated by Django 4.1.4 on 2023-01-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app32", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="teach_Reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.IntegerField()),
                ("place", models.CharField(max_length=100)),
                ("post", models.CharField(max_length=100)),
                ("pin_code", models.IntegerField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("role", models.CharField(max_length=20)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app32.login"
                    ),
                ),
            ],
        ),
    ]
